[package]
name = "collpasswd"
version = "0.4.0"
edition = "2021"

[dependencies]
# Web framework
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }

# Database
rusqlite = { version = "0.31", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.24"

# Auth & crypto
argon2 = "0.5"
jsonwebtoken = "9"
p256 = { version = "0.13", features = ["ecdh", "pem"] }
aes-gcm = "0.10"
hkdf = { version = "0.12", features = ["std"] }
rand = "0.8"
sha2 = "0.10"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
rust-embed = "8"
mime_guess = "2"



# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Misc
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.22"
uuid = { version = "1", features = ["v4"] }
zeroize = { version = "1", features = ["zeroize_derive", "alloc"] }
clap = { version = "4", features = ["derive"] }
libc = "0.2"
axum-server = { version = "0.7", features = ["tls-rustls"] }
rcgen = "0.12.1"
time = { version = "0.3", features = ["formatting"] }
